namespace AIPlatform.Core.Models;

public class ExecutionPlanResponse
{
    // The "Blueprint" generated by the AI
    public string Goal { get; set; }
    public List<PlanStep> Steps { get; set; } = new();
}

public class PlanStep
{
    public int StepId { get; set; }
    public string ToolId { get; set; } // The Service or Agent to run
    public string ToolType { get; set; } // "DataService", "AIService", "Agent"
    public string Description { get; set; }

    // Inputs the tool needs. 
    // The AI will map these to previous steps (e.g., "UserId": "{{Step1.Output.Id}}")
    public Dictionary<string, string> InputMapping { get; set; } = new();
}